# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from internal.cvcio.classification import accounts_pb2 as cvcio_dot_classification_dot_accounts__pb2


class AccountServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectTwitterAccount = channel.unary_unary(
                '/classification.AccountService/DetectTwitterAccount',
                request_serializer=cvcio_dot_classification_dot_accounts__pb2.TwitterAccount.SerializeToString,
                response_deserializer=cvcio_dot_classification_dot_accounts__pb2.ResponseAccount.FromString,
                )


class AccountServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectTwitterAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectTwitterAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectTwitterAccount,
                    request_deserializer=cvcio_dot_classification_dot_accounts__pb2.TwitterAccount.FromString,
                    response_serializer=cvcio_dot_classification_dot_accounts__pb2.ResponseAccount.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'classification.AccountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccountService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectTwitterAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/classification.AccountService/DetectTwitterAccount',
            cvcio_dot_classification_dot_accounts__pb2.TwitterAccount.SerializeToString,
            cvcio_dot_classification_dot_accounts__pb2.ResponseAccount.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
