# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cvcio/classification/comments.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from internal.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from internal.cvcio.common import meta_pb2 as cvcio_dot_common_dot_meta__pb2
from internal.cvcio.common import predictions_pb2 as cvcio_dot_common_dot_predictions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cvcio/classification/comments.proto',
  package='classification',
  syntax='proto3',
  serialized_options=b'Z+github.com/cvcio/proto/cvcio/classification',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#cvcio/classification/comments.proto\x12\x0e\x63lassification\x1a\x1cgoogle/api/annotations.proto\x1a\x17\x63vcio/common/meta.proto\x1a\x1e\x63vcio/common/predictions.proto\"3\n\x07\x43omment\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1a\n\x04meta\x18\x02 \x01(\x0b\x32\x0c.common.Meta\"8\n\rResponseToxic\x12\'\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x12.common.Prediction*\xaf\x01\n\x0c\x43ommentClass\x12\r\n\tROLE_HATE\x10\x00\x12\x1f\n\x1bROLE_ETHNIC_IDENTITY_ATTACK\x10\x01\x12\x0f\n\x0bROLE_INSULT\x10\x02\x12\x16\n\x12ROLE_LAW_AND_ORDER\x10\x03\x12\x14\n\x10ROLE_NATIONALISM\x10\x04\x12\x1f\n\x1bROLE_GENDER_IDENTITY_ATTACK\x10\x05\x12\x0f\n\x0bROLE_THREAT\x10\x06\x32y\n\x0e\x43ommentService\x12g\n\x0b\x44\x65tectToxic\x12\x17.classification.Comment\x1a\x1d.classification.ResponseToxic\" \x82\xd3\xe4\x93\x02\x1a\"\x15/v3/comments/toxicity:\x01*B-Z+github.com/cvcio/proto/cvcio/classificationb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,cvcio_dot_common_dot_meta__pb2.DESCRIPTOR,cvcio_dot_common_dot_predictions__pb2.DESCRIPTOR,])

_COMMENTCLASS = _descriptor.EnumDescriptor(
  name='CommentClass',
  full_name='classification.CommentClass',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ROLE_HATE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROLE_ETHNIC_IDENTITY_ATTACK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROLE_INSULT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROLE_LAW_AND_ORDER', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROLE_NATIONALISM', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROLE_GENDER_IDENTITY_ATTACK', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROLE_THREAT', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=254,
  serialized_end=429,
)
_sym_db.RegisterEnumDescriptor(_COMMENTCLASS)

CommentClass = enum_type_wrapper.EnumTypeWrapper(_COMMENTCLASS)
ROLE_HATE = 0
ROLE_ETHNIC_IDENTITY_ATTACK = 1
ROLE_INSULT = 2
ROLE_LAW_AND_ORDER = 3
ROLE_NATIONALISM = 4
ROLE_GENDER_IDENTITY_ATTACK = 5
ROLE_THREAT = 6



_COMMENT = _descriptor.Descriptor(
  name='Comment',
  full_name='classification.Comment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='classification.Comment.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta', full_name='classification.Comment.meta', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=193,
)


_RESPONSETOXIC = _descriptor.Descriptor(
  name='ResponseToxic',
  full_name='classification.ResponseToxic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='predictions', full_name='classification.ResponseToxic.predictions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=251,
)

_COMMENT.fields_by_name['meta'].message_type = cvcio_dot_common_dot_meta__pb2._META
_RESPONSETOXIC.fields_by_name['predictions'].message_type = cvcio_dot_common_dot_predictions__pb2._PREDICTION
DESCRIPTOR.message_types_by_name['Comment'] = _COMMENT
DESCRIPTOR.message_types_by_name['ResponseToxic'] = _RESPONSETOXIC
DESCRIPTOR.enum_types_by_name['CommentClass'] = _COMMENTCLASS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Comment = _reflection.GeneratedProtocolMessageType('Comment', (_message.Message,), {
  'DESCRIPTOR' : _COMMENT,
  '__module__' : 'cvcio.classification.comments_pb2'
  # @@protoc_insertion_point(class_scope:classification.Comment)
  })
_sym_db.RegisterMessage(Comment)

ResponseToxic = _reflection.GeneratedProtocolMessageType('ResponseToxic', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSETOXIC,
  '__module__' : 'cvcio.classification.comments_pb2'
  # @@protoc_insertion_point(class_scope:classification.ResponseToxic)
  })
_sym_db.RegisterMessage(ResponseToxic)


DESCRIPTOR._options = None

_COMMENTSERVICE = _descriptor.ServiceDescriptor(
  name='CommentService',
  full_name='classification.CommentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=431,
  serialized_end=552,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetectToxic',
    full_name='classification.CommentService.DetectToxic',
    index=0,
    containing_service=None,
    input_type=_COMMENT,
    output_type=_RESPONSETOXIC,
    serialized_options=b'\202\323\344\223\002\032\"\025/v3/comments/toxicity:\001*',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMENTSERVICE)

DESCRIPTOR.services_by_name['CommentService'] = _COMMENTSERVICE

# @@protoc_insertion_point(module_scope)
