# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/rtaa/classification/common/v1/meta.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.proto/rtaa/classification/common/v1/meta.proto\x12#proto.rtaa.classification.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x02\n\x04Meta\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n\x06source\x18\x02 \x01(\tR\x06source\x12\x1f\n\x0bscreen_name\x18\x03 \x01(\tR\nscreenName\x12H\n\x12\x63omment_created_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x10\x63ommentCreatedAt\x12\x42\n\x0fuser_created_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ruserCreatedAt\x12?\n\rclassified_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0c\x63lassifiedAt\x12\x12\n\x04link\x18\x07 \x01(\tR\x04link\x12\x12\n\x04lang\x18\x08 \x01(\tR\x04lang\x12\x1c\n\tthreshold\x18\t \x01(\x01R\tthreshold\x12\x18\n\x07version\x18\n \x01(\tR\x07versionB\xe5\x01\n\'com.proto.rtaa.classification.common.v1B\tMetaProtoP\x01\xa2\x02\x04PRCC\xaa\x02#Proto.Rtaa.Classification.Common.V1\xca\x02#Proto\\Rtaa\\Classification\\Common\\V1\xe2\x02/Proto\\Rtaa\\Classification\\Common\\V1\\GPBMetadata\xea\x02\'Proto::Rtaa::Classification::Common::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.rtaa.classification.common.v1.meta_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'com.proto.rtaa.classification.common.v1B\tMetaProtoP\001\242\002\004PRCC\252\002#Proto.Rtaa.Classification.Common.V1\312\002#Proto\\Rtaa\\Classification\\Common\\V1\342\002/Proto\\Rtaa\\Classification\\Common\\V1\\GPBMetadata\352\002\'Proto::Rtaa::Classification::Common::V1'
  _META._serialized_start=121
  _META._serialized_end=503
# @@protoc_insertion_point(module_scope)
