# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/rtaa/classification/comments/v1/comments.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from proto.rtaa.classification.common.v1 import meta_pb2 as proto_dot_rtaa_dot_classification_dot_common_dot_v1_dot_meta__pb2
from proto.rtaa.classification.common.v1 import predictions_pb2 as proto_dot_rtaa_dot_classification_dot_common_dot_v1_dot_predictions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4proto/rtaa/classification/comments/v1/comments.proto\x12%proto.rtaa.classification.comments.v1\x1a\x1cgoogle/api/annotations.proto\x1a.proto/rtaa/classification/common/v1/meta.proto\x1a\x35proto/rtaa/classification/common/v1/predictions.proto\"\\\n\x07\x43omment\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text\x12=\n\x04meta\x18\x02 \x01(\x0b\x32).proto.rtaa.classification.common.v1.MetaR\x04meta\"Y\n\x0b\x43ommentList\x12J\n\x08\x63omments\x18\x01 \x03(\x0b\x32..proto.rtaa.classification.comments.v1.CommentR\x08\x63omments\"\xa1\x01\n\rResponseToxic\x12Q\n\x0bpredictions\x18\x01 \x03(\x0b\x32/.proto.rtaa.classification.common.v1.PredictionR\x0bpredictions\x12=\n\x04meta\x18\x02 \x01(\x0b\x32).proto.rtaa.classification.common.v1.MetaR\x04meta\"e\n\x11ResponseToxicList\x12P\n\x08\x63omments\x18\x01 \x03(\x0b\x32\x34.proto.rtaa.classification.comments.v1.ResponseToxicR\x08\x63omments2\xe1\x02\n\x0e\x43ommentService\x12\x9f\x01\n\rClassifyToxic\x12..proto.rtaa.classification.comments.v1.Comment\x1a\x34.proto.rtaa.classification.comments.v1.ResponseToxic\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v3/classify/comment/toxicity\x12\xac\x01\n\x11\x43lassifyToxicList\x12\x32.proto.rtaa.classification.comments.v1.CommentList\x1a\x38.proto.rtaa.classification.comments.v1.ResponseToxicList\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v3/classify/comments/toxicityB\xf3\x01\n)com.proto.rtaa.classification.comments.v1B\rCommentsProtoP\x01\xa2\x02\x04PRCC\xaa\x02%Proto.Rtaa.Classification.Comments.V1\xca\x02%Proto\\Rtaa\\Classification\\Comments\\V1\xe2\x02\x31Proto\\Rtaa\\Classification\\Comments\\V1\\GPBMetadata\xea\x02)Proto::Rtaa::Classification::Comments::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.rtaa.classification.comments.v1.comments_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.proto.rtaa.classification.comments.v1B\rCommentsProtoP\001\242\002\004PRCC\252\002%Proto.Rtaa.Classification.Comments.V1\312\002%Proto\\Rtaa\\Classification\\Comments\\V1\342\0021Proto\\Rtaa\\Classification\\Comments\\V1\\GPBMetadata\352\002)Proto::Rtaa::Classification::Comments::V1'
  _COMMENTSERVICE.methods_by_name['ClassifyToxic']._options = None
  _COMMENTSERVICE.methods_by_name['ClassifyToxic']._serialized_options = b'\202\323\344\223\002\":\001*\"\035/v3/classify/comment/toxicity'
  _COMMENTSERVICE.methods_by_name['ClassifyToxicList']._options = None
  _COMMENTSERVICE.methods_by_name['ClassifyToxicList']._serialized_options = b'\202\323\344\223\002#:\001*\"\036/v3/classify/comments/toxicity'
  _COMMENT._serialized_start=228
  _COMMENT._serialized_end=320
  _COMMENTLIST._serialized_start=322
  _COMMENTLIST._serialized_end=411
  _RESPONSETOXIC._serialized_start=414
  _RESPONSETOXIC._serialized_end=575
  _RESPONSETOXICLIST._serialized_start=577
  _RESPONSETOXICLIST._serialized_end=678
  _COMMENTSERVICE._serialized_start=681
  _COMMENTSERVICE._serialized_end=1034
# @@protoc_insertion_point(module_scope)
